### ISSUE TITLE
Test Script appears to be broken

### ISSUE THREAD

**Issue by DChandlerP** [ebi-gene-expression-group/r-seurat-scripts#18]
The error I'm getting is. 

I'm getting it from inside the quay.io/biocontainers/seurat-scripts:0.0.6--0 container.

wget: not an http or ftp url: https://s3-us-west-2.amazonaws.com/10x.files/samples/cell/pbmc3k/pbmc3k_filtered_gene_bc_matrices.tar.gz
env: can't execute 'bats': No such file or directory

Despite raising this issue I have to say that it's awesome this program actually has a test script. I've gone through about 50 programs for bioinformatics in the past two weeks and this is the first one I've seen that has one! It's very useful to instantly know whether everything works correctly! I hope this gets fixed!!!

**Comment by pcm32** [comment]
Hi, thanks for reporting it. 

We use the testing previous to the construction of the container in the CI of this repo, before merging from feature branches, normally in a conda environment. You can see that tests for the last merge were passed here https://travis-ci.org/ebi-gene-expression-group/r-seurat-scripts/builds/613568825?utm_source=github_status&utm_medium=notification 

The container is built later on automatically by the bioconda CI based on the conda package built from this repo, so it might be that in the conda package meta.yaml specification we might not have added all the dependencies needed for the testing as we normally don't run it at that point in the container and to keep the container lighter. I will take a look, but if this is the case, I would probably leave like that. That would explain the missing bats part and possibly wget not having https support/certificates inside the container.

In the meantime, if you want to run the tests, I would suggest doing a checkout and following the steps used in the .travis.yml file for making sure that you have all deps and that the test are run as expected.

We also have https://github.com/ebi-gene-expression-group/scanpy-scripts/ and ways of running all of these plus others from Galaxy (https://toolshed.g2.bx.psu.edu/view/ebi-gxa) if you are interested.
