### ISSUE TITLE
Make a pr to bioconda soon to enable more fluid collaboration

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/r-seurat-scripts#3]
I was pointed to existing efforts in wrapping seurat for Galaxy https://github.com/galaxyproject/tools-iuc/pull/2047#issuecomment-416830101. Towards collaborating with them and to avoid duplication that will later be regretted by both users and us, we should make a first PR to bioconda to add r-seurat-scripts there.

**Comment by pcm32** [comment]
Ping @pinin4fjords

**Comment by pinin4fjords** [comment]
Okay @pcm32, will tidy up metadata and do this ASAP
